// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozfjqdgoaobazydtsjel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96ZmpxZGdvYW9iYXp5ZHRzamVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODgzMjcsImV4cCI6MjA2MTk2NDMyN30.updSQMtoYdKAjomMgdDKamFkRAXCC9xVdZ8ol70PGFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);